name: cicd

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - 'main'
    types:
      - opened
      - reopened
      - synchronize

jobs:
  cicd:
    name: cicd
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        id: checkout
        uses: actions/checkout@v3

      - name: Setup Node
        id: setup_node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install Dependency
        id: install_dependency
        run: |
          yarn install

      - name: Build
        id: build
        run: |
          yarn build

    #   - name: Run test
    #     id: run_test
    #     run: |
    #       yarn test
